apiVersion: v1
kind: ServiceAccount
metadata:
  name: max-user
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: max-user-role
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: max-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: max-user-role
subjects:
- kind: ServiceAccount
  name: max-user
  namespace: default
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  max_ip: "max-image-caption-generator"
---
apiVersion: v1
kind: Service
metadata:
  name: max-image-caption-generator
spec:
  selector:
    app: max-image-caption-generator
  ports:
  - port: 5000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: max-image-caption-generator
  labels:
    app: max-image-caption-generator
spec:
  selector:
    matchLabels:
      app: max-image-caption-generator
  replicas: 1
  template:
    metadata:
      labels:
        app: max-image-caption-generator
    spec:
      containers:
      - name: max-image-caption-generator
        image: quay.io/codait/max-image-caption-generator:latest
        ports:
        - containerPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: max-image-front-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: max-image-front-deployment
  template:
    metadata:
      labels:
        app: max-image-front-deployment
    spec:
      serviceAccountName: max-user
      containers:
        - name: max-image-front-container
          image: yichengzhu/max-image_front:050904
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: max-image-front-service
spec:
  type: LoadBalancer
  selector:
    app: max-image-front-deployment
  ports:
  - port: 5000
      
