apiVersion: apps/v1
kind: Deployment
metadata:
  name: max-image-front-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: max-image-front
  template:
    metadata:
      labels:
        app: max-image-front
    spec:
      containers:
        - name: max-image-front
          image: yicheng_zhu/max-image_front:0508
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: max-image-front-service
spec:
  selector:
    app: max-image-front
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
  externalIPs:
    - 192.168.0.10