apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: max-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: max-user-role
subjects:
- kind: ServiceAccount
  name: max-user
  namespace: default